adb shell pm uninstall -k --user 0 com.amazon.kindle
adb shell pm uninstall -k --user 0 com.asus.livedemo
adb shell pm uninstall -k --user 0 com.asus.microfilm
adb shell pm uninstall -k --user 0 com.asus.ia.asusapp
adb shell pm uninstall -k --user 0 com.android.wallpaper
adb shell pm uninstall -k --user 0 com.android.dreams.basic
adb shell pm uninstall -k --user 0 com.android.galaxy4
adb shell pm uninstall -k --user 0 com.android.noisefield
adb shell pm uninstall -k --user 0 com.android.phasebeam
adb shell pm uninstall -k --user 0 com.google.android.calendar
adb shell pm uninstall -k --user 0 com.google.android.providers.calendar
adb shell pm uninstall -k --user 0 com.cleanmaster.mguard
adb shell pm uninstall -k --user 0 com.cmcm.skey
adb shell pm uninstall -k --user 0 com.cleanmaster.security
adb shell pm uninstall -k --user 0 com.facebook.appmanager
adb shell pm uninstall -k --user 0 com.facebook.system
adb shell pm uninstall -k --user 0 com.facebook.katana
adb shell pm uninstall -k --user 0 com.facebook.orca
adb shell pm uninstall -k --user 0 com.cleanmaster.mguard
adb shell pm uninstall -k --user 0 com.asus.task
adb shell pm uninstall -k --user 0 com.asus.quickmemo
adb shell pm uninstall -k --user 0 com.asus.playto
adb shell pm uninstall -k --user 0 com.asus.sharerim
adb shell pm uninstall -k --user 0 com.asus.supernote
adb shell pm uninstall -k --user 0 com.asus.weathertime
adb shell pm uninstall -k --user 0 com.asus.userfeedback
adb shell pm uninstall -k --user 0 com.asus.zentalk
adb shell pm uninstall -k --user 0 com.asus.themeapp
adb shell pm uninstall -k --user 0 com.asus.collage
adb shell pm uninstall -k --user 0 com.asus.setupwizard
adb shell pm uninstall -k --user 0 com.ironsource.appcloud.oobe.asus
adb shell pm uninstall -k --user 0 com.ecareme.asuswebstorage
adb shell pm uninstall -k --user 0 com.gameloft.android.GloftPZOO
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.google.android.apps.docs
adb shell pm uninstall -k --user 0 com.google.android.videos
adb shell pm uninstall -k --user 0 com.google.android.music
adb shell pm uninstall -k --user 0 com.google.android.tts
adb shell pm uninstall -k --user 0 com.google.android.apps.photos
adb shell pm uninstall -k --user 0 com.google.android.apps.maps
adb shell pm uninstall -k --user 0 com.google.android.talk
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.marvin.talkback
adb shell pm uninstall -k --user 0 com.instagram.android
adb shell pm uninstall -k --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall -k --user 0 com.google.android.feedback
adb shell pm uninstall -k --user 0 com.android.providers.userdictionary