/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Unlock": "解锁",
    "Your": "你的",
    "Factors": "因子",
    "galaxy link": "星系链接",
    // "Hyper Game": "超级游戏",
    "hyper-points": "超级点数",
    "Locked!": "未解锁！",
    "On": "开启",
    "Number": "数字",
    "Requires": "需要",
    "Recent cascades:": "最近的级联：",
    "Currently x": "当前 x",
    "Reach certain amounts of shadow crystals to achieve shadow milestones!": "达到一定数量的 暗影水晶 即可实现暗影里程碑！",
    "Ordinal Pringles": "序数品客（Ordinal Pringles）",
    "other projects": "其它项目",
    "Manual save": "手动保存",
    "Cluster limit:": "集群限制：",
    "Cluster upgrade respec confirmation:": "集群升级 重洗 确认：",
    "Cluster upgrades are always bought at no cost": "集群升级始终免费购买",
    "Cluster your number [+": "对您的号码进行集群 [+",
    "Clusters": "集群",
    "Clusters (": "集群 (",
    "The end": "终点",
    "times/second": "次/秒",
    "total)": "总计)",
    "To be unlocked...": "待解锁...",
    "vectors per second": "向量每秒",
    "vectors": "向量",
    "Vectors": "向量",
    "Vectors no longer divide factor production (except in challenge 5)": "向量不再除以因子生产（挑战 5 除外）",
    "Shadow milestones": "暗影里程碑",
    "shadow power": "暗影之力",
    "shadow power/s (based on current hyper-points)": "暗影之力每秒（基于你当前的超级点数）",
    "shadow power gives you": "暗影之力给你",
    "Surpass the limits of cascade and go beyond!": "超越级联的极限，超越！",
    "the Basedverse": "基础宇宙",
    "up-base": "升级基础",
    "down-base": "降低基础",
    "This will allow you to gain more than 1 cascade per reset.": "这将使您在每次重置时获得超过 1 个级联。",
    "Recent": "最近",
    "Reset your number to gain": "重置您的数字以获得",
    "Hard reset": "硬重置",
    "Increase your number (I)": "提高你的数字（I）",
    "Gain max multipliers (M)": "获得最大乘数（M）",
    "challenges": "挑战",
    "Challenges": "挑战",
    "Each factor produces the one before it. 1st factors produce autoclickers.": "每一个因子都会产生它之前的一个因子。 第一个因子产生自动点击器。",
    "Enable vector gain": "启用向量增益",
    "Hyper-E": "超级-E",
    "(based on current number, only if vector gain is enabled)": "基于当前数量，仅当向量增益启用时）",
    "(The cluster limiter will not work if you already have more clusters than the limit)": "（如果您的集群数量已超过限制，集群限制器将不起作用）",
    "Also unlocks flavours": "还解锁了 flavours",
    "and": "和",
    "an autobuyer for factors (at no cost)": "一个因子自动购买器（免费）",
    "Auto-base shift:": "自动基数偏移：",
    "autoclickers are clicking the increase button": "自动点击器正在点击提高按钮",
    "Automatically buy post-cascade upgrade 1 at no cost": "自动免费购买级联后升级1",
    "Automatically gain clusters without resetting": "自动获取集群，无需重置（",
    "auto-base shift": "自动基数偏移",
    "base points": "基础点数",
    "base points (": "基础点数 (",
    "Base points": "基础点数",
    "Base points respec confirmation:": "基础点数 重洗 确认：",
    "blood crystals": "血液水晶",
    "Blood crystals multiply shadow power/s": "血液水晶乘以暗影力量/秒",
    "blood crystals, multiplying shadow power/s by": "血液水晶，乘以暗影力量/秒",
    "blood power": "血液力量",
    "blood power/s (based on current shadow power)": "血液力量/秒（基于你当前的暗影力量）",
    "blood power gives you": "血液力量给你",
    "Buy max factors (F)": "购买最大因子 (F)",
    "Buy max layers (F)": "购买最大层 (F)",
    "Cascade": "级联",
    "Cascade confirmation:": "级联确认：",
    "Cascade power effect is improved": "级联力量效果被提升了",
    "Cascade power, multiplying factor production by": "级联力量，乘以因子生产",
    "Cascade with certain amounts of clusters or less to achieve cascade milestones!": "级联一定数量或更少的集群，以实现级联里程碑！",
    "Exit current challenge": "退出当前挑战",
    "Factor autobuyer:": "因子自动购买器",
    "something...": "一些东西...",
    "Respec base points": "重洗基础点数",
    "Respec clusters": "重洗集群",
    "Reset previous progress to gain a cascade (C)": "重置之前的进度以获得级联 (C)",
    "Shadow crystals": "暗影水晶",
    "Shadow crystals multiply divine power/s": "暗影水晶乘以神圣力量/秒",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "1st factor ": "第 1 因子 ",
    "2nd factor ": "第 2 因子 ",
    "3rd factor ": "第 3 因子 ",
    "1st layer ": "第 1 层 ",
    "2nd layer ": "第 2 层 ",
    "3rd layer ": "第 3 层 ",
    "Unlock ": "解锁 ",
    "Reset vectors to ": "将向量重置为 ",
    "Gain an autoclicker multiplier ": "获得一个自动点击器乘数 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^你(.+)$/,
    /^挑战(.+)$/,
    /^成本(.+)$/,
    /^(.+)集群$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)E([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Each (.+) costs$/, '每个 $1 成本'],
    [/^Requires (.+) in base (.+)$/, '需要 $1 到基数 $2'],
    [/^(.+), multiplying (.+) gain by$/, '$1，乘以 $2 增益 '],
    [/^You are gaining (.+) blood crystal every$/, '你获得 $1 血液水晶 每'],
    [/^You are gaining (.+) divine crystal every$/, '你获得 $1 神圣水晶 每'],
    [/^You are gaining (.+) shadow crystal every$/, '你获得 $1 暗影水晶 每'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Beat challenge ([\d\.,]+) once$/, '完成挑战 $1 一次'],
    [/^Beat challenge ([\d\.,]+) ([\d\.,]+) times$/, '完成挑战 $1 $2 次'],
    [/^Challenge ([\d\.,]+) \($/, '挑战 $1（'],
    [/^([\d\.,]+)th factor (.+)$/, '第 $1 因子 $2'],
    [/^([\d\.,]+)th layer (.+)$/, '第 $1 层 $2'],
    [/^([\d\.,]+) in base ([\d\.,]+)$/, '$1 到基数 $2'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) crystals$/, '$1 水晶'],
    [/^([\d\.,]+) crystal$/, '$1 水晶'],
    [/^([\d\.,]+) clusters$/, '$1 集群'],
    [/^([\d\.,]+) hyper\-points$/, '$1 超级点数'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Costs (.+) shadow power$/, '成本 $1 暗影力量'],
    [/^Costs (.+) hyper\-points$/, '成本 $1 超级点数'],
    [/^Costs (.+) cascades$/, '成本 $1 级联'],
    [/^Requires (.+) clusters$/, '需要 $1 集群'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);